apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: edgedeployments.grin.pucrs.br
spec:
  group: grin.pucrs.br
  version: v1alpha1
  scope: Namespaced
  subresources:
    status: {}
  names:
    plural: edgedeployments
    singular: edgedeployment
    kind: EdgeDeployment
    shortNames:
    - edeploy
  additionalPrinterColumns:
  - name: Regions
    type: integer
    description: The number of regions launched by the Edge Deployment
    JSONPath: .status.regions
  - name: Pods
    type: integer
    description: The number of pods launched by the Edge Deployment
    JSONPath: .status.pods
  - name: Age
    type: date
    JSONPath: .metadata.creationTimestamp
  - name: Regions Names
    type: string
    JSONPath: .status.regionsNames
    priority: 10